### PR TITLE
Add optional handling of meta files

### PR DESCRIPTION
**Pull request by Bartheleway**
I tried to write some stuff but I'm really not a VS Code extensions writter so I don't know how to test it or if there are better ways to write what I did.

Feel free to comment and I will try to correct it.

### CODE REVIEW

**Comment by daishi4u** [comment]
I will look it over, I have a couple changes I would like to make to it. I have a constant for handling the api version and I'd like to include the package.xml if that option is true, but other than that it's looking good. One other thing is I'll have to add code back in for pushing the metadata as well because I removed that too.

**Comment by daishi4u** [comment]
It was removed in the compile.ts file. You could compare mine to celador's to see the changes. I could even merge this and then I could add the part back in the compile.ts file if you would like.

**Comment by Bartheleway** [comment]
I did try to find what changed but I think I lack of understanding. So if you have time for this, I will appreciate that you do it :)

**Comment by daishi4u** [comment]
OK I will work on it when I get time. For now I will merge this, thanks for your work 😀

**Pull request merged**
